const menus = [
  {
    "ModuleId": "",
    "AppId": 1,
    "ParentId": 0,
    "FullName": "行政办公",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 11,
    "ParentId": 1,
    "FullName": "组织单位",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 111,
    "ParentId": 11,
    "FullName": "组织单位1",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 1111,
    "ParentId": 111,
    "FullName": "单位职能1",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 1112,
    "ParentId": 111,
    "FullName": "单位职能1",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 1113,
    "ParentId": 111,
    "FullName": "单位职能1",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 112,
    "ParentId": 11,
    "FullName": "组织单位2",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 1121,
    "ParentId": 112,
    "FullName": "单位职能2",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 1122,
    "ParentId": 112,
    "FullName": "单位职能3",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 1123,
    "ParentId": 112,
    "FullName": "单位职能4",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 12,
    "ParentId": 1,
    "FullName": "工作流程",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 121,
    "ParentId": 12,
    "FullName": "人员考勤",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 1211,
    "ParentId": 121,
    "FullName": "考勤排班",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 1212,
    "ParentId": 121,
    "FullName": "考勤管理",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 1213,
    "ParentId": 121,
    "FullName": "我的考勤",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 1214,
    "ParentId": 121,
    "FullName": "打卡管理",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 122,
    "ParentId": 12,
    "FullName": "薪资福利",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 1221,
    "ParentId": 122,
    "FullName": "薪资管理",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 1222,
    "ParentId": 122,
    "FullName": "工资管理",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 1223,
    "ParentId": 122,
    "FullName": "薪资用户",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 1224,
    "ParentId": 122,
    "FullName": "我的工资",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 123,
    "ParentId": 12,
    "FullName": "人员排班",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 1231,
    "ParentId": 123,
    "FullName": "排班模版",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 12322,
    "ParentId": 123,
    "FullName": "排班管理",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 1233,
    "ParentId": 123,
    "FullName": "我的考勤",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 1234,
    "ParentId": 123,
    "FullName": "打卡管理",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 124,
    "ParentId": 12,
    "FullName": "招聘管理",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 1241,
    "ParentId": 124,
    "FullName": "建立管理",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 1242,
    "ParentId": 124,
    "FullName": "人才管理",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 1243,
    "ParentId": 124,
    "FullName": "代办管理",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 1244,
    "ParentId": 124,
    "FullName": "打卡管理",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 125,
    "ParentId": 12,
    "FullName": "人员考勤",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 1251,
    "ParentId": 125,
    "FullName": "考勤排班",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 1252,
    "ParentId": 125,
    "FullName": "考勤管理",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 1253,
    "ParentId": 125,
    "FullName": "我的考勤",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 1254,
    "ParentId": 125,
    "FullName": "打卡管理",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 13,
    "ParentId": 1,
    "FullName": "人事行政",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 14,
    "ParentId": 1,
    "FullName": "公共信息",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 15,
    "ParentId": 1,
    "FullName": "投票管理",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 2,
    "ParentId": 0,
    "FullName": "财务系统",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 21,
    "ParentId": 2,
    "FullName": "人事行政",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 22,
    "ParentId": 2,
    "FullName": "人事行政",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 23,
    "ParentId": 2,
    "FullName": "人事行政",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 24,
    "ParentId": 2,
    "FullName": "公共信息",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 25,
    "ParentId": 2,
    "FullName": "投票管理",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 3,
    "ParentId": 0,
    "FullName": "分析系统",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 4,
    "ParentId": 0,
    "FullName": "测量工具",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 41,
    "ParentId": 4,
    "FullName": "Option1",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 411,
    "ParentId": 41,
    "FullName": "Option411",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 412,
    "ParentId": 41,
    "FullName": "Option412",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 413,
    "ParentId": 41,
    "FullName": "Option413",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 42,
    "ParentId": 4,
    "FullName": "Option42",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 43,
    "ParentId": 4,
    "FullName": "Option43",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 5,
    "ParentId": 0,
    "FullName": "第三方应用",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 51,
    "ParentId": 5,
    "FullName": "Option51",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 511,
    "ParentId": 51,
    "FullName": "Option511",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 5111,
    "ParentId": 511,
    "FullName": "Option5111",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 5112,
    "ParentId": 511,
    "FullName": "Option5112",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 5113,
    "ParentId": 511,
    "FullName": "Option5113",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 512,
    "ParentId": 51,
    "FullName": "Option512",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 5121,
    "ParentId": 512,
    "FullName": "班组管理",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 5122,
    "ParentId": 512,
    "FullName": "班组管理理",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 5123,
    "ParentId": 512,
    "FullName": "班组管理理理",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 513,
    "ParentId": 51,
    "FullName": "Option513",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 52,
    "ParentId": 5,
    "FullName": "Option52",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 53,
    "ParentId": 5,
    "FullName": "Option53",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 6,
    "ParentId": 0,
    "FullName": "维护平台",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  },
  {
    "ModuleId": "",
    "AppId": 7,
    "ParentId": 0,
    "FullName": "项目管理",
    "UrlAddress": "",
    "Target": "",
    "IsMenu": "",
    "IsPublic": "",
    "CreateDate": "",
    "CreateUserName": "",
    "ModifyDate": "",
    "ModifyUserName": ""
  }
]

export default menus;